name: Deploy to Production
on:
  workflow_dispatch: {}

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Theme (twentytwentyfour)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          sftp_only: true
          local_path: "twentytwentyfour/*"
          remote_path: "/home/s1149026/gustolocal.es/wp-content/themes/twentytwentyfour"
          remove_extra_files: false

      - name: Deploy Plugin (weekly-meal-builder)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          sftp_only: true
          local_path: "weekly-meal-builder/*"
          remote_path: "/home/s1149026/gustolocal.es/wp-content/plugins/weekly-meal-builder"
          remove_extra_files: false
